# Generated by Django 5.0.14 on 2026-06-20 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'surveys_survey',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('question_text', models.JSONField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multi_choice', 'Multiple Choice'), ('text', 'Free Text'), ('scale', 'Rating Scale'), ('boolean', 'Yes/No'), ('ranking', 'Ranking'), ('matrix', 'Matrix Grid'), ('date', 'Date Input'), ('time', 'Time Input'), ('audio_response', 'Audio Dictation')], max_length=50)),
                ('options', models.JSONField(blank=True, null=True)),
                ('routing_rules', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey')),
            ],
            options={
                'db_table': 'surveys_question',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['survey', 'order'], name='surveys_que_survey__d73192_idx')],
            },
        ),
    ]
