# Generated by Django 5.0.14 on 2026-06-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.JSONField(),
        ),
    ]
