# Generated by Django 5.0.14 on 2026-06-20 17:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(default='participant', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_user',
            },
        ),
        migrations.CreateModel(
            name='AccessibilityPreferences',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('speech_rate', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('speech_volume', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('text_scale', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('high_contrast', models.BooleanField(default=False)),
                ('reduced_motion', models.BooleanField(default=False)),
                ('preferred_voice', models.CharField(default='default', max_length=100)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='accessibility_preferences', to='users.user')),
            ],
            options={
                'db_table': 'users_accessibilitypreferences',
            },
        ),
    ]
